name: "Auto Assign"
on:
  project_card:
    issues:
      types: [assigned]
  
jobs:
  assign_reviewer:
    runs-on: macos-latest
    steps:
      - name: git_action_test
        with:
          config: '.github/auto-assigner.yml'
          token: ${{ secrets.GITHUB_TOKEN }}
