name: "Auto Assign"
on:
  issues:
    types: [assigned]
  
jobs:
  assign_reviewer:
    runs-on: macos-latest
    steps:
    - uses: shufo/auto-assign-reviewer-by-assignee@v1.1.0
      with:
        config: '.github/auto-assigner.yml'
        token: ${{ secrets.GITHUB_TOKEN }}
